### ISSUE TITLE
Instant untag player when the region flag pvp is changing

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#10]
### Description

Hello, I have such a suggestion and also a problem.

A player who is in a region that has -> pvp allow (worldguard) is in combat mode with another player is fighting with him. 

The third player (the owner of the region which is not in combat mode) changes the flag to pvp deny and the player who is not added to this region can't move because he is in combat mode.

### Category

Combat

### Configuration

In worldguard support - add a function when the flag on the region is changing to pvp dedny all the players who are in combat mode are untaged from combat instant.

**Comment by UnitedCraft** [comment]
Is there anything being done towards this feature?

**Comment by timderspieler** [comment]
Fixed with the next version. Thank you for your report @UnitedCraft :)
