### ISSUE TITLE
[Bug] Hpets potion effects while in pvp

### ISSUE THREAD

**Issue by ArcticTroxx** [timderspieler/DeluxeCombat-Issues#11]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Paper 1.19

### Your discord name

ArcticTroxx#8618

### Current Behavior

While a player has a pet equipped they receive a potion effect (example: saturation). This will heavily impact the pvp aspect of the server if the effect isn't removed while in pvp.

### Expected Behavior

I would like the effects to be disabled once in pvp and to turn back on once out of combat tag.

### Steps To Reproduce

Enable a pet with an effect (example: saturation)

Attack a player

See that the effect is still there while in combat tag.

### Frequency

100% of the time.

### Anything else?

Nope, thank you for your time.

**Comment by timderspieler** [comment]
Status: Waiting for the author to get back from his vacation.

**Comment by timderspieler** [comment]
Solved with: https://github.com/Heron4gf/hpet/commit/24ba6088f1ce1d17c27a9b2dc815b30550c90e95
