### ISSUE TITLE
[Bug] Players don't get untagged after they die (not always)

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#13]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur 1.18.2

### Your discord name

RavenskyPaul#1249

### Current Behavior

My players found a strange bug with death/teleporting.
After they die, they are respawned on /spawn and they got combat timer and somehow get teleported when they die.

This option is disabled:
![image](https://user-images.githubusercontent.com/79587189/184711996-97d0bc46-dc65-4a13-b23e-b5519d41eb95.png)

Video
https://cdn.discordapp.com/attachments/943229962712924170/1008781556447449199/2022-08-15_12-08-26.mp4

### Expected Behavior

When players die after fight combat is off

### Steps To Reproduce

https://cdn.discordapp.com/attachments/943229962712924170/1008781556447449199/2022-08-15_12-08-26.mp4

### Frequency

Not always 20-50%

**Comment by UnitedCraft** [comment]
On 50 second in the video we can see that the dead player attack again that player... I think its with fire

**Comment by timderspieler** [comment]
Update:

issue could be caused by the victim which hits the other player with fire aspect.
-> burn delay after death
-> victim gets re-tagged after respawn 
-> victim gets teleported back

**Comment by UnitedCraft** [comment]
After the player dies, the last strike is from the thorns on the armor. 100% recreate

**Comment by timderspieler** [comment]
Solved with commit: [6c26e3e](https://github.com/timderspieler/DeluxeCombat/commit/6c26e3ee89fcba4b42179fd281de21c1a3d20146)
