### ISSUE TITLE
[Bug] Player can see vanished players with /pvpstats command

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#14]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur 1.18.2

### Your discord name

RavenskyPaul#1249

### Current Behavior

![unknown2](https://user-images.githubusercontent.com/79587189/184713686-1d3ed84d-0035-45cd-a43c-1e104e2e9082.png)

### Expected Behavior

Add a support to premium vanish. When someone is vanished. It must look like they are offline

### Steps To Reproduce

![unknown2](https://user-images.githubusercontent.com/79587189/184713686-1d3ed84d-0035-45cd-a43c-1e104e2e9082.png)

### Frequency

100%

**Comment by timderspieler** [comment]
Solved with commit [849fce4](https://github.com/timderspieler/DeluxeCombat/commit/849fce413ad644f37199e0d33bdb18173bc6cb14)
