### ISSUE TITLE
[Bug] problem with toggle pvp

### ISSUE THREAD

**Issue by haroldrc** [timderspieler/DeluxeCombat-Issues#17]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Paper 1.18.2

### Your discord name

harold#1385

### Current Behavior

if i put the pvp OFF i can take damage from "endcystal and anchor" if they are placed by a player

### Expected Behavior

take no damage

### Steps To Reproduce

place an end crystal and detonate it

### Frequency

100% of the time

**Comment by timderspieler** [comment]
Solved with commit [ece750c](https://github.com/timderspieler/DeluxeCombat/commit/ece750c145b654e06a7e35fdc22c8ca49ed661aa)
