### ISSUE TITLE
/dc untag all

### ISSUE THREAD

**Issue by yngdrms** [timderspieler/DeluxeCombat-Issues#19]
### Description

Perhaps somehow add to the console command /dc untag all, so that before the restart you can execute this command and no one dies?
![image](https://user-images.githubusercontent.com/79171955/189542332-d947b954-fdb4-45e3-9bea-53340d650716.png)

### Category

Combat

### Configuration

A simple command that can be used without interacting with /dc menu

**Comment by timderspieler** [comment]
Added with commit https://github.com/timderspieler/DeluxeCombat/commit/942edbe50fc8f57d2c64ccf2d4a752b54a40e519
