### ISSUE TITLE
Bounty Glow Won't Disappear

### ISSUE THREAD

**Issue by jcool3413** [timderspieler/DeluxeCombat-Issues#22]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Paper 1.19.2

### Your discord name

jcool3413#3200

### Current Behavior

So, the bounty glow effect won't disappear even if the player doesn't have a bounty.

### Expected Behavior

I expected the glow to disappear.

### Steps To Reproduce

I don't know exactly what happened but I will give a brief overview.

1. Have a bounty
2. Disable the glow effect 

### Frequency

100% of the time

**Comment by timderspieler** [comment]
Thank you for your bug report! It will be fixed with the next version!
