### ISSUE TITLE
[Bug] error

### ISSUE THREAD

**Issue by ProtoGhost** [timderspieler/DeluxeCombat-Issues#25]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

1.12.2

### Your discord name

ProtoGhost#9599

### Current Behavior

[DeluxeCombat] Couldn't hook into ShopGUI+ due to a incompatibility. Please report this to the author.

### Expected Behavior

[DeluxeCombat] Couldn't hook into ShopGUI+ due to a incompatibility. Please report this to the author.

### Steps To Reproduce

[DeluxeCombat] Couldn't hook into ShopGUI+ due to a incompatibility. Please report this to the author.

### Frequency

[DeluxeCombat] Couldn't hook into ShopGUI+ due to a incompatibility. Please report this to the author.

### Anything else?

[DeluxeCombat] Couldn't hook into ShopGUI+ due to a incompatibility. Please report this to the author.

**Comment by timderspieler** [comment]
This error can be ignored since it does not interfere with the plugins functionality. ShopGUI+ support will be removed with the next update.
