### ISSUE TITLE
[Feature Request] DiscordSRV integration hook for forwarding DeluxeCombat death messages

### ISSUE THREAD

**Issue by Opalinium** [timderspieler/DeluxeCombat-Issues#29]
### Description

**As the DeluxeCombat death messages are non-standard, they currently aren't able to be detected by DiscordSRV for death-message forwarding, which can be a minor hindrance for those that wish to forward such messages to their respective discord servers. I would like to request an integration hook for DiscordSRV to allow death-messages to be forwarded as per normal.
Thank you kindly in advance!**

### Category

Supported Plugins

### Configuration

Toggle_Feature: Boolean Setting

**Comment by timderspieler** [comment]
I have added an option to override the default death message with the new custom death message. With this it should be possible to simply use the PlayerDeathEvent to integrate the DeluxeCombat death messages into DiscordSRV.

https://github.com/timderspieler/DeluxeCombat/commit/8e6acbf3724283202d80ac3cb555cf3bf5e3ed74
