### ISSUE TITLE
[Bug] Incompatibility with AureliumSkills' bleeding effect

### ISSUE THREAD

**Issue by Folas1337** [timderspieler/DeluxeCombat-Issues#3]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Paper 1.19 build 66

### Your discord name

Folas1337#1988

### Current Behavior

If you hit a user that has PvP disabled, you can still apply AureliumSkills' bleeding effect.

### Expected Behavior

The bleeding effect should be prevented by DeluxeCombat

### Steps To Reproduce

1. Install AureliumSkills
2. Install DeluxeCombat
3. Hit someone while having a high enough fighting skill to enable bleeding

### Frequency

It always happens when you would apply the bleeding effect. Depending on your fighting level of AureliumSkills this can vary in how often it tries to apply but every time it tries, it goes through.

### Anything else?

I've mentioned this on Discord before and it's been fixed for the bleeding enchantment of AdvancedEnchantments, now I'd love to have it for AureliumSkills too :)

**Comment by timderspieler** [comment]
The bug cannot be fixed at the current stage of the AureliumSkills plug-in. The author mentioned to add the corresponding api soon.

**Comment by Folas1337** [comment]
> The bug cannot be fixed at the current stage of the AureliumSkills plug-in. The author mentioned to add the corresponding api event soon.

So we wait until that happens and leave the ticket open or does that mean you'll close it and I'll have to recreate it when it's available?
I'd prefer the former myself 😅

**Comment by timderspieler** [comment]
> > The bug cannot be fixed at the current stage of the AureliumSkills plug-in. The author mentioned to add the corresponding api event soon.
> 
> So we wait until that happens and leave the ticket open or does that mean you'll close it and I'll have to recreate it when it's available? I'd prefer the former myself 😅

Yes! We'll wait until @Archi-X adds the needed event to his API :)

**Comment by timderspieler** [comment]
Feature request: https://github.com/Archy-X/AureliumSkills/issues/115

**Comment by Folas1337** [comment]
I'm no longer using Deluxe combat so this isn't of interest for me anymore
