### ISSUE TITLE
[Bug] or [Feature Request] Players can open writable books during combat with active prevent function

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#31]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur 1.18.2

### Your discord name

RavenskyPaul#1249

### Current Behavior

![image](https://user-images.githubusercontent.com/79587189/204093476-55fe27ac-f804-4cf6-9220-73a7d02f878e.png)

I have blocked all types of books, and player can open a writable book during combat

### Expected Behavior

Players can't open books during combat mode

### Steps To Reproduce

1. Go in to combat mode
2. Open a writable book
3. Write something there
4. Close the book, and You have a book with Your text writed during combat mode.

### Frequency

100%

**Comment by timderspieler** [comment]
Hey @UnitedCraft ,

thank you for your feature request. I can confirm that you can open books during combat even though its disabled via the "Disable Item Interaction" list. Sadly, the animation when opening a book is handled by the client. That means I can't cancel or prevent it with my plugin.

What I can prevent though is the book from being written after the player has closed the book interface. This has been added with the commit https://github.com/timderspieler/DeluxeCombat/commit/547f31ece438c5b8ddf4008c2f345206918016b8

If you need further help with this issue. Please reopen this issue :)
