### ISSUE TITLE
Bed explosions when pvptoggle is disabled

### ISSUE THREAD

**Issue by razorrider7** [timderspieler/DeluxeCombat-Issues#33]
### Description

DeluxeCombat's current PVP toggle implementation prevents placing beds in nether/end dimensions, but not sleeping in them if already placed. It would probably be better to prevent sleeping in the area of another player who has PVP disabled.

This would also allow players to mine in the nether with beds, so long as nobody else is nearby to be damaged by it or the fire they spawn.

### Category

PvP

### Configuration

N/A

**Comment by timderspieler** [comment]
Changed with commit https://github.com/timderspieler/DeluxeCombat/commit/c5e4b57e85c6789e22323c564baab9828fac7190

Thank you for feature request :)
