### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dopii2** [timderspieler/DeluxeCombat-Issues#35]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

git-Purpur-1854 (MC: 1.19.2)

### Your discord name

Law#0550

### Current Behavior

When you type / while being in Combat you get a spam error in the console

### Expected Behavior

Using / while in combat shouldnt return anything, however it spams the console which it shouldnt

### Steps To Reproduce

Player enters combat
Player types /
Console spams error messages

### Frequency

Happens everytime you do / while in combat

### Anything else?

 I asked my dev about it and he said a list length check in the class nl.marido.deluxecombat.listeners.CommandListener in the isBlockedCommand function would fix the issue

https://imgur.com/a/TPREKUK

**Comment by timderspieler** [comment]
Fixed with commit https://github.com/timderspieler/DeluxeCombat/commit/a0f275f6d7769a5dcb1b41aa56fa4c3c9d2ff9a1

Thank you for your report!
