### ISSUE TITLE
New minecraft version.

### ISSUE THREAD

**Issue by dinobossytnew** [timderspieler/DeluxeCombat-Issues#36]
### Description

Add support for the new version 1.19.3 if required in my tests the plugin did not load in this version and there is no error.

### Category

General

### Configuration

does not need.

**Comment by timderspieler** [comment]
Hey DinoBoss,

I have updated the plugin to library v.1.19.3 with the commit: https://github.com/timderspieler/DeluxeCombat/commit/6992e1e2909304294c9a65f2d8c626634b7acd0b

The plugin started just fine for me without changing anything especially for 1.19.3. In case there are still issues after the next update, please reopen this issue.

greetings
