### ISSUE TITLE
[Feature Request] Enable a setting to modify collisionRule of vanilla teams

### ISSUE THREAD

**Issue by Folas1337** [timderspieler/DeluxeCombat-Issues#4]
### Description

If you enable the vanilla teams to make people's name appear in red, you get two of those teams called "dc-pvp-true" and "dc-pvp-false" but their collisionRule is set to teamOnly or whatever but I would like it to be always because otherwise you can not push any entities (like villagers or mobs) anymore.
For now I'm using the following commands every time my server restarts but it'd obviously be way nicer to have this included in the plugin instead:
> team modify dc-pvp-true collisionRule always
> team modify dc-pvp-false collisionRule always

### Category

General

### Configuration

A toggle where you can set all 4 options of the teams collisionRule individually, which would be Always, Never, pushOtherTeams and pushOwnTeam

So two buttons, one for pvp-true and one for pvp-false where you can cycle through those 4 options.

**Comment by timderspieler** [comment]
Added with commit: [bdba037](https://github.com/timderspieler/DeluxeCombat/commit/bdba0379e723dc5145a7f25751d0b99d66426f9b)
