### ISSUE TITLE
More placeholders

### ISSUE THREAD

**Issue by Kukizzz2** [timderspieler/DeluxeCombat-Issues#43]
### Description

Can you make an extra placeholder like `%deluxecombat_ranking_<StatsType>_<Rank>_name% ` but output only name...
`%deluxecombat_ranking_<StatsType>_<Rank>_name%` - kukizz_
`%deluxecombat_ranking_<StatsType>_<Rank>_<Stats>%` - 2                    *(Stats: kills, deaths, combatlogs, points)*

Example:

`%deluxecombat_ranking_kills_1_name%` - kukizz_
`%deluxecombat_ranking_kills_1_kills%` - 2

### Category

Ranking System

### Configuration

.

**Comment by timderspieler** [comment]
Hey Kukizzz,

this has been added with DeluxeCombat v.1.40.8 :)

Thank you for the idea!
