### ISSUE TITLE
[Bug] Potion flags tag player into combat even with CMI Invulnerability

### ISSUE THREAD

**Issue by bobhenl** [timderspieler/DeluxeCombat-Issues#45]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

git-Purpur-1906 (MC: 1.19.3)

### Your discord name

Renzotom#6586

### Current Behavior

Players are combat tagged even when they don't receive damage when they teleport to some player using /tpa when they throw some potion on them (harming or poison for example). This is something that CMI plugin solves with it's option:
```
    # Time in seconds player should be invulnerable after teleporting
    # This will prevent player who teleported to damage others for defined time
    # Set this to 0 if you want to disable it
    # Max 60 seconds
    Invulnerability: 15
```

but it seems that DeluxeCombat doesn't respect it... 

### Expected Behavior

Players shouldn't be attacked (that's correct now via using CMI Invulnerability) and they shouldn't be combat tagged. So if they've got tp trapped they can tp away.

### Steps To Reproduce

1. Use CMI & Invulnerability option.
2. Teleport to some player using /tpa
3. Let him attack you - he cannot cause you are protected after teleport
4. Now let him throw potion on you -> you'll be combat tagged!
5. And now you cannot escape from him

### Frequency

It happens 100% of time when you do this.

**Comment by timderspieler** [comment]
Thank you very much for your report! The bug will be fixed with the next version of DeluxeCombat!
