### ISSUE TITLE
[Bug] Gsit incompatible with DeluxeCombat after update

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#5]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur 1.18.2

### Your discord name

RavenskyPaul#1249

### Current Behavior

I have the latest version of gsit and I have this message after server start:
```[04:03:55 ERROR]: [DeluxeCombat] DeluxeCombat is incompatible with your version of GSit. Please update your copy of the GSit plugin!
[04:03:55 ERROR]: [DeluxeCombat] Couldn't hook into GSit due to a incompatibility. Please report this to the author.```

### Expected Behavior

No error after server start

### Steps To Reproduce

Update DeluxeCombat with GSIT API

### Frequency

100%

### Anything else?

_No response_

**Comment by timderspieler** [comment]
Fixed with commit: a22e5a88f0583ba626515e1f874dbd36e75c5955
