### ISSUE TITLE
New Loot option Victim OR Killer

### ISSUE THREAD

**Issue by MikeHollisJr2021** [timderspieler/DeluxeCombat-Issues#50]
### Description

Describe as well as you can about the feature you're requesting
It seems odd that the options to loot a corpse include victim or killer, but not victim and killer.  

to me it seems to make more sense to allow the killer to loot in pvp and also the person who's stuff it is / was

### Category

PvP

### Configuration

N/A

**Comment by timderspieler** [comment]
Thank you for your feature request :) The feature will be added with DeluxeCombat v.1.40.5!
