### ISSUE TITLE
[Bug] Can't enable nether bed mining for players with pvp off

### ISSUE THREAD

**Issue by matipoirierg** [timderspieler/DeluxeCombat-Issues#52]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur-1962 1.19.4

### Your discord name

maty#5498

### Current Behavior

I have allow-nether-bed-place: true but players still can't make the beds explode, when they try to sleep they receive a message saying "You cant do that right now!" They only can make the bed explode if they have their pvp enabled but I want users with pvp disabled to use this.

### Expected Behavior

Players with pvp off should be able to make beds explode on nether

### Steps To Reproduce

listed above

### Frequency

100%

**Comment by timderspieler** [comment]
Fixed with next update (DeluxeCombat v.1.40.5)! Thank you for your report!

**Comment by matipoirierg** [comment]
> Fixed with next update (DeluxeCombat v.1.40.5)! Thank you for your report!

Sorry a lil bit confused, did you mean 1.40.6 since the one you mention is the actual one
