### ISSUE TITLE
Shopgui+ hook error!

### ISSUE THREAD

**Issue by 00Hrtz** [timderspieler/DeluxeCombat-Issues#57]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Paper 1.19.4 #526

### Your discord name

sircraftypants#4875

### Current Behavior

Shopgui+ Hook Error

### Expected Behavior

I checked other reports and the last time the same thing was reported was back in Oct 2022 where you stated shopgui+ wouldn't be supported in the next version.

Did you mean support for shopgui+ was ending permanently or just for a while?

As I'm getting this with the latest version of deluxecombat as of 09/05/2023

,,,yaml
[12:51:25 ERROR]: [DeluxeCombat] Couldn't hook into ShopGUI+ due to a incompatibility. Please report this to the author.

If permanently can you remove the error check please, appreciated.

### Steps To Reproduce

Check current deluxecombat with the latest shopgui+ as of today's above date.

### Frequency

100% of time.

**Comment by 00Hrtz** [comment]
I've disabled the hook for now.

**Comment by timderspieler** [comment]
The hook has been removed. Thank you for the report.
