### ISSUE TITLE
[Bug] Destroy armorstands, itemframes, open chests in combat mode

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#6]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur 1.18.2

### Your discord name

RavenskyPaul#1249

### Current Behavior

 I can destroy armorstands, and take/put items to chests during the fight (also with itemframes added also to the list)

### Expected Behavior

 I cant destroy armorstands, and take/put items to chests during the fight (also with itemframes added also to the list) on combat mode

### Steps To Reproduce

/dc menu, settings, PvP, extras and add the chests / blocks to the disable interact with blocks list and armor stands, item frames to the entity list - enabled option “Only during combat”

### Frequency

100%

**Comment by timderspieler** [comment]
Update: Disabling the interaction works but players can still destroy armorstands.

**Comment by timderspieler** [comment]
Solved with commit [4e6d2a7](https://github.com/timderspieler/DeluxeCombat/commit/4e6d2a751490cec2a1036dae6a5ae9df6c5ae817)
