### ISSUE TITLE
[Bug] could not pass playerdeathevent

### ISSUE THREAD

**Issue by xF3d33** [timderspieler/DeluxeCombat-Issues#60]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

pufferfish 1.19.4

### Your discord name

DeadPyro_
#0017

### Current Behavior

![image](https://github.com/timderspieler/DeluxeCombat-Issues/assets/67204462/8d6d2807-9fa5-453c-a02b-539fbdf1d833)

### Expected Behavior

no errors

### Steps To Reproduce

just dying in some circumstances 

### Frequency

50% i think

**Comment by JasperTheMinecraftDev** [comment]
Provide the full log using a paste or codeblocks.

**Comment by timderspieler** [comment]
Has been fixed with v.1.50.2! Thank you for the report.
