### ISSUE TITLE
[Bug] Citizens NPC's have Healthbars

### ISSUE THREAD

**Issue by 00Hrtz** [timderspieler/DeluxeCombat-Issues#61]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Paper 1.19.4 #530

### Your discord name

sircraftypants#4875

### Current Behavior

My Citizens NPC's have healthbars, i'm told this shouldn't be happening, i don't want them to have it.

### Expected Behavior

No healthbars on npc's.

### Steps To Reproduce

install latest paper and DeluxeCombat with Citizens and enable healthbars in DeluxeCombat

### Frequency

constant

**Comment by timderspieler** [comment]
Hey SirCraftypants,

this is sadly an issue with minecraft and citizens specificly. (See: https://wiki.citizensnpcs.co/Frequently_Asked_Questions#There's_a_%220_health%22_line_below_my_NPC's_names ). It cannot be fixed.

greetings
Tim
