### ISSUE TITLE
Command /deathback should't teleport if the player dies from void damage

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#62]
### Description

Deathback command shouldn't teleport player to last death place if the player falls into a void (void damage) - works only on world_the_end.

### Category

Death

### Configuration

Toggle_Feature: Death -> /deathback command (prevent teleport to void)

**Comment by timderspieler** [comment]
Has been added and fixed with the next update. Thank you for the report :)
