### ISSUE TITLE
OP commands to change stats kills, deaths. (similar to kill points.)

### ISSUE THREAD

**Issue by ghost** [timderspieler/DeluxeCombat-Issues#63]
### Description

Add commands with limited permissions so that you can change the kills, deaths statistics, similar to the one that is currently available with kill points.

Command example:
/pvpkills (add,remove,set) (player) (amount)
/pvpdeaths (add,remove,set) (player) (amount)

### Category

Ranking System

### Configuration

This function, in theory, should not be in the GUI menu of the plugin.

**Comment by timderspieler** [comment]
Added! (Available with the next update.)
