### ISSUE TITLE
[Bug] The /bounty command glow red. (but works)

### ISSUE THREAD

**Issue by ghost** [timderspieler/DeluxeCombat-Issues#65]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

DeluxeCombat version - 1.40.8 (https://imgur.com/a/FYKbK7D)
Server version - git-Purpur1857 (MC:1.19.2)* (https://imgur.com/a/LZT2Lon)

### Your discord name

Samparo#7144

### Current Behavior

Bounty system, when I have permission and write the /bounty command in the chat, it glows red, as if this command does not exist. (but it still works). Also, since the command is glowing red, the arguments also do not appear in the floating line. I changed this /bounty > /killer command in the DeluxeCombat plugin and this aliase also glows red.

### Expected Behavior

When you start writing this command or its alias, it should glow as if it is on the server and further command arguments will appear.

### Steps To Reproduce

1. Just start typing the /bounty command in chat or your alise of this system.

### Frequency

Always. Even after restarting the server.

### Anything else?

Photo: https://imgur.com/a/3Xnw4Ep

**Comment by timderspieler** [comment]
The command glows red since it hasn't been registered as a command. This is due to the fact that DeluxeCombat only registers the /bounty command as a custom command. It can be changed within the /dc menu. We have decided to take this route since a lot of servers already have a boutny plugin. Like this, the DeluxeCombat bounty does not interferre with those plugins.

Thank you anyways for the report. Maybe there will be a possibility to change this in the future!

**Comment by ghost** [comment]
> The command glows red since it hasn't been registered as a command. This is due to the fact that DeluxeCombat only registers the /bounty command as a custom command. It can be changed within the /dc menu. We have decided to take this route since a lot of servers already have a boutny plugin. Like this, the DeluxeCombat bounty does not interferre with those plugins.
> 
> Thank you anyways for the report. Maybe there will be a possibility to change this in the future!

the usual /bounty command was also glowing red...

**Comment by timderspieler** [comment]
Yes the /bounty command is the custom one. The "real" bounty command is /deluxecombat-bounty.

**Comment by ghost** [comment]
> Yes the /bounty command is the custom one. The "real" bounty command is /deluxecombat-bounty.

can you make subcommands glow? /dc is a subcommand, but it glows as it should.
