### ISSUE TITLE
[Bug] When Off-Hand is disabled, you can use the F key in the inventory

### ISSUE THREAD

**Issue by YahBoyTUGG** [timderspieler/DeluxeCombat-Issues#68]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

git-Paper-307 (MC: 1.19.2)

### Your discord name

Aлехандро#1288

### Current Behavior

In the Old PvP category the off-hand is set to be disabled. When pressing the "Swap Item With Offhand" keybinding it cancels the event normally, same when trying to drag the item to the offhand through the inventory BUT if you click on the keybinding while hovering over the item in the inventory it still places the item in the offhand slot.

### Expected Behavior

Expected behavior should be the blocking of the "Swap Item With Offhand" keybinding, inventory drag and inventory and usage of the keybinding while hovering over the item.

### Steps To Reproduce

1. Open the DeluxeCombat Menu
2. Got to Settings
3. Go to the Old PvP category
4. Click on "Old PvP"
5. Active the "Disable Offhand"
6. Take an item, open the inventory
7. Hover over the item and click the keybinding.

### Frequency

It happens 100% of the time.

### Anything else?

https://github.com/timderspieler/DeluxeCombat-Issues/assets/67952616/73b9bd69-e85f-40ee-bc3a-468b06526002

**Comment by timderspieler** [comment]
Thank you for the report! I have fixed the issue.
