### ISSUE TITLE
[Bug]  Firework don't put you in combat when hit feet

### ISSUE THREAD

**Issue by bobhenl** [timderspieler/DeluxeCombat-Issues#69]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

[18:14:17 INFO]: Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Purpur-1933 (MC: 1.19.3)
* You are running the latest version

### Your discord name

renzotom

### Current Behavior

Fireworks dont put you in combat if fired from a crossbow
https://cdn.discordapp.com/attachments/762982810616594442/1120378837335801956/Minecraft__1.19.3_2023-06-17_05-51-09.mp4

### Expected Behavior

Fireworks should put you in combat when hit feet

### Steps To Reproduce

make a maxed out firework crossbow
shoot feet of players
kill them without combat and stuff

### Frequency

it happens 100% when you hit feet

**Comment by bobhenl** [comment]
https://streamable.com/33plyl BTW, fireworks also ignores the Grace, so players keep killing new players with the firework rockets.

**Comment by timderspieler** [comment]
The issue has been fixed! The fix will be available with the next update. Thank you very much for your report :)
