### ISSUE TITLE
DeluxeCombat's title methods break titles

### ISSUE THREAD

**Issue by Fredh1000** [timderspieler/DeluxeCombat-Issues#70]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Tested on:
WindSpigot 1.8.8
Spigot 1.8.8

### Your discord name

fredh1000

### Current Behavior

DeluxeCombat breaks the titles of every plugin in my server, doesn't show them, or after playing for a while, shows them for less time than it should be.
Example: https://www.youtube.com/watch?v=E7fUgxK7dic

How did I figure out that it could be an inherent problem with DeluxeCombat?
When I enter the server and there is DeluxeCombat in the server, it happens that I don't see the titles for each plugin. To understand that it was actually a DeluxeCombat problem I tried to restart the server once, again with DeluxeCombat inside, but not to enter the server, so as to avoid the DeluxeCombat message that says: [DeluxeCombat] [Titles] Alright, we don't use the bukkit methods now! And which, consequently, will break the titles. If I avoid entering the server, so as not to allow DeluxeCombat to modify the methods (apparently forever), the next restart, removing DeluxeCombat, the titles will reappear.
If, on the other hand, I restart the server, log into the server and have DeluxeCombat modify the titles methods, on the next restart, by removing DeluxeCombat, the titles will remain broken and invisible.

### Expected Behavior

I expected the titles of the other plugins to remain unchanged, without being "broken" in the way described above.

### Steps To Reproduce

1) Put DeluxeCombat on the server together with a plugin that displays titles (like SaberFactions).
2) In the case of SaberFactions you will need to claim a chunk.
3) Entering and exiting the chunk, the title will not appear, or it will appear for less than 1-2 seconds (which shouldn't happen).

### Frequency

It happens every time DeluxeCombat is on the server. It also happens if on reboot before boot without DeluxeCombat, a user joins the server and causes DeluxeCombat to fire its titles methods (message: [DeluxeCombat] [Titles] Alright, we don't use the bukkit methods now!)

**Comment by timderspieler** [comment]
Thank you for the report. The fix for the issue will be available with the next update.
