### ISSUE TITLE
[Bug] Anti kill abuse - combat mode doesn't end after killing a player

### ISSUE THREAD

**Issue by UnitedCraft** [timderspieler/DeluxeCombat-Issues#77]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Kyanette-1.20.1

### Your discord name

ravenskypaul

### Current Behavior

When You have active anti kill abuse - when player gets banned - combat mode on damager doesn't end when he kill the same player

### Expected Behavior

Combat mode ends after killing that player

### Steps To Reproduce

1. Enable antikill abuse
2. Set ban player after 1 kill
3. kill him twice
4. That second time combat mode will not end after killing

### Frequency

100%

**Comment by timderspieler** [comment]
Fixed with the next update. Thank you for your report :)
