### ISSUE TITLE
CombatTag Display [Hex Color]

### ISSUE THREAD

**Issue by Zsomi** [timderspieler/DeluxeCombat-Issues#8]
### Description

It would be a more minor function to color the action bar. Which would mean that not only the primary Minecraft colors could be used, but also hex colors.

### Category

Combat

### Configuration

You could specify the color with a simple /dc setvalue [hex color] command.

**Comment by timderspieler** [comment]
Added for the next release: https://github.com/timderspieler/DeluxeCombat/commit/fbc907708436ec491d678ec60efdafa5bbffa01b
