### ISSUE TITLE
[Bug] Typo

### ISSUE THREAD

**Issue by ItzAndriss** [timderspieler/DeluxeCombat-Issues#80]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

1.18.2

### Your discord name

itzandriss

### Current Behavior

It is described at Steps To Reproduce

### Expected Behavior

It is described at Steps To Reproduce

### Steps To Reproduce

- /deluxecombat menu
- Settings
- Rewards: Break after first success
![image](https://github.com/timderspieler/DeluxeCombat-Issues/assets/81358652/a6688e0d-52fc-4922-b3a9-f644fff6e63b)

### Frequency

It is described at Steps To Reproduce

**Comment by timderspieler** [comment]
Thanks for the report! I've fixed it :)
