### ISSUE TITLE
NotBounties

### ISSUE THREAD

**Issue by dinobossytnew** [timderspieler/DeluxeCombat-Issues#83]
### Description

I don't know how to explain it, but I need to be able to disable the bounties feature that comes with DeluxeCombat, which is very basic, so that I can interact only with notbounties.

### Category

Supported Plugins

### Configuration

https://www.spigotmc.org/resources/notbounties.104484/

api https://github.com/No-Not-Jaden/NotBounties/wiki/API

**Comment by timderspieler** [comment]
Hey @dinobossytnew !
To disable the bounty feature, please go to /dc menu, settings, pvp, bounty and disable the options.

To prevent Deluxecombat from using the /bounty command, set the bounty alias inside the bounty menu to something different.
