### ISSUE TITLE
[Bug] Theres an issue with your worldguard addon

### ISSUE THREAD

**Issue by plateou** [timderspieler/DeluxeCombat-Issues#9]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

1.19

### Your discord name

Plateou#0001

### Current Behavior

They just spam break wall and the small knockback gives them invulnerability and makes them not take damage meaning they could wait out the combat tag time.

### Expected Behavior

They do not go invincible and instead just get hit and combat tagged.

### Steps To Reproduce

1. Run to the worldguard wall
2. Get tagged
3. Break the wall
4. Get little knockback that makes you invulnerable
5. Do it until combat tag runs out
6. Then your safe.

### Frequency

100%

### Anything else?

https://www.youtube.com/watch?app=desktop&v=uGenEasMA0I

**Comment by timderspieler** [comment]
The bug has been confirmed.

Steps to resolve:

- Option to disable the interact knockback
- Knockback when trying to traverse the border
- Combat timer reset on interact
- Damage on interact

**Comment by timderspieler** [comment]
Bugfix is working for the beta testers.
