### ISSUE TITLE
Hook for Husk Claims

### ISSUE THREAD

**Issue by Kruseified** [timderspieler/DeluxeCombat-Issues#92]
### Description

I am requesting a hook to be added for Husk Claims

- Allow pvp in claims if the player was already tagged outside of the claim rather then protecting them.
- Or add a border system for claims to keep players using them to escape

### Category

PvP

**Comment by timderspieler** [comment]
Hello @Kruseified :)

Thank you for the suggestion. There already is a hook available for Husk Claims in the addon store of DeluxeCombat. Simply open the /dc menu, go to Addons, Marketplace and download the HuskClaims Addon!

**Comment by Kruseified** [comment]
Hey! Was this added recently? As I just set it up and there was not lol, I see it now but now I am questioning my eye sight lol

**Comment by timderspieler** [comment]
Has been added around ~3 weeks ago :)

I am glad that it works now for you!
